# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab18a9fc5bb45f4ce3c52f36950e3348f118c698f65aa2f76a74fc284a5aba0fc6dc0d44925a761a864124a6c28cf3eec9e025796a2371a16081ef07dc958176

test:
  secret_key_base: 3d68857726194df1cce2e5eba218d7a97350b899349e4f86fd4cde24925a0f1b8d41082806cf2ac997f62dec02a839b1e3812e85b158853c9714e909b7069711

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
